chore: develop (NEXI)_2_main
pagopa/pagopa-mock-ec pull request #72
Opened 2024-11-19 18:26 UTC by pasqualespica

#### List of Changes

- preliminary preparations for updating  mock-ec to SANP 3.10
- updated az devops internal and nexi pipeline 
- added helm chart 

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2025-11-13 11:30 UTC, aomegax requested changes

2025-11-13 11:30 UTC, aomegax commented on .nexiazuredevops/pipeline-build-and-deploy.yml
> +  repository_primary: 'mock-ec-primary'
please, rollback all modification in this file because it belongs to Nexi env

2025-11-13 11:30 UTC, aomegax commented on helm/values-it.yaml
> +microservice-chart: &microservice-chart
(this env should be removed)

2025-11-13 11:30 UTC, aomegax commented on helm/values-prf.yaml
> +      memory: "1Gi"
200m

2025-11-13 11:44 UTC, matteo-raiola commented on helm/values-it.yaml
> +microservice-chart: &microservice-chart
i am using it as an anchor for mock-primary, mock-secondary, and mock-ec-replica config

2026-02-18 11:01 UTC, pasqualespica commented
replaced b https://github.com/pagopa/pagopa-mock-ec/pull/84

2026-02-18 11:01 UTC, closed without merging